name: Website Tracker

on:
  schedule:
    - cron: "0 9 * * *" # Run at 9 AM and 9 PM UTC
  workflow_dispatch:       # Allow manual triggering

jobs:
  track_website:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: master

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 python-dotenv
        ls -la

    - name: Run Website Tracker
      run: python tracker/main.py

    - name: Debug Git Status
      run: |
        echo "Debugging Git Status"
        ls -la
        git status

    - name: Check for Changes
      id: check_changes
      run: |
        if git diff --quiet data/website_state.json; then
          echo "No changes in website_state.json"
          echo "skip_commit=true" >> $GITHUB_ENV
        else
          echo "Changes detected in website_state.json"
          echo "skip_commit=false" >> $GITHUB_ENV
        fi

    - name: Commit Updated State
      if: env.skip_commit == 'false'
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add data/website_state.json
        git commit -m "Update website state"
        git push

    - name: Send Email
      if: env.skip_commit == 'false'
      uses: dawidd6/action-send-mail@v4
      with:
        connection_url: ${{ secrets.MAIL_CONNECTION }}
        subject: "Website Tracker: New Listings"
        to: ${{ secrets.RECIPIENT_EMAIL }}
        from: "Website Tracker <${{ secrets.EMAIL }}>"
        body: file://data/email_content.html