name: Website Tracker

on:
 # schedule:
 #   - cron: "0 9 * * *" # Run at 9 AM UTC every day
  workflow_dispatch:       # Allow manual triggering

jobs:
  track_website:
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Website Tracker
      run: python tracker/main.py

    - name: Debug Git Status
      run: |
        echo "Debugging Git Status"
        ls -la
        git status
        echo "Current branch: $(git branch --show-current)"
        echo "Last commit: $(git log -1 --oneline)"

    - name: Check for Changes
      id: check_changes
      run: |
        set -e
        if git ls-files --error-unmatch data/website_state.json > /dev/null 2>&1; then
          echo "File is tracked. Checking for changes..."
          if git diff --quiet data/website_state.json; then
            echo "No changes in website_state.json"
            echo "changes_detected=false" >> $GITHUB_OUTPUT
            echo "skip_commit=true" >> $GITHUB_ENV
          else
            echo "Changes detected in website_state.json"
            echo "changes_detected=true" >> $GITHUB_OUTPUT
            echo "skip_commit=false" >> $GITHUB_ENV
          fi
        else
          echo "File is untracked or missing. Changes assumed."
          echo "changes_detected=true" >> $GITHUB_OUTPUT
          echo "skip_commit=false" >> $GITHUB_ENV
        fi

    - name: Commit Updated State
      if: env.skip_commit == 'false'
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add data/website_state.json
        git commit -m "Update website state"
        git push

    - name: Send Email
      if: env.skip_commit == 'false'
      uses: dawidd6/action-send-mail@c624d7739b2e058d9177b3bbafc528ffddfccaa7 #v4
      with:
        connection_url: ${{ secrets.MAIL_CONNECTION }}
        subject: "Website Tracker: New Listings"
        to: ${{ secrets.RECIPIENT_EMAIL }}
        from: "Website Tracker <${{ secrets.EMAIL }}>"
        body: file://data/email_content.txt
