name: Website Tracker

on:
  schedule:
    - cron: "0 9,21 * * *" # Run at 9 AM and 9 PM UTC
  workflow_dispatch:       # Allow manual triggering

jobs:
  track_website:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 python-dotenv

    - name: Run Website Tracker
      run: python tracker/main.py

    - name: Send Email
      uses: dawidd6/action-send-mail@v4
      with:
        connection_url: ${{ secrets.MAIL_CONNECTION }}
        subject: "Website Tracker: New Listings"
        to: ${{ secrets.RECIPIENT_EMAIL }}
        from: "Website Tracker <${{ secrets.EMAIL }}>"
        body: file://email_content.html
